backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # tempat gambar disimpan
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Artikel"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar Sampul", name: "thumbnail", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }