backend:
  name: github
  repo: mangdev8/blog-mangdev8  # Ganti sesuai username dan nama repo kamu
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Artikel"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi", name: "body", widget: "markdown" }
      - { label: "Gambar", name: "thumbnail", widget: "image" }